version: '2'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
    container_name: es
    ports:
      - "9200:9200"
      #- "9300:9300"
    environment:
      # ES_JAVA_OPTS: "-Xms2g -Xmx2g"
      discovery.type: single-node
    # volumes:
    #   - /root/log/elasticsearch/data:/usr/share/elasticsearch/data
    networks:
      - elk

  # logstash:
  #   image: docker.elastic.co/logstash/logstash:6.2.4
  #   ports:
  #     - "5000:5000"
  #   networks:
  #     - elk
  #   depends_on:
  #     - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.0
    container_name: kibana
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: bridge